apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-app
  template:
    metadata:
      labels:
        app: one-app
    spec:
      containers:
      - name: one-app
        image: __ECR_IMAGE__  # Placeholder for the ECR image URI
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-secret
