apiVersion: apps/v1
kind: Deployment
metadata:
  name: one_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one_app
  template:
    metadata:
      labels:
        app: one_app
    spec:
      containers:
      - name: one_app
        image: __ECR_IMAGE__  # Placeholder for the ECR image URI
        ports:
        - containerPort: 8080
